M48
; DRILL file {KiCad (7.0.0)} date Fri May  5 13:18:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-05T13:18:49-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X4.2853Y-5.1177
X4.5987Y-2.2177
X5.1121Y-5.1177
X5.9853Y-5.1177
X6.8121Y-5.1177
T2
X3.6Y-2.2
X3.6Y-5.0
X7.8Y-2.2
X7.8Y-5.0
T0
M30
